name: Backend Lint and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Change to API directory
      working-directory: ./api
      run: echo "Moved to API directory"

    - name: Install dependencies
      working-directory: ./api
      run: |
        poetry install

    - name: Run Ruff lint check
      working-directory: ./api
      run: poetry run ruff check .

    - name: Run tests
      working-directory: ./api
      run: |
        poetry run pytest
